include::00_header.adoc[]

= Requirements

== Database

* *tblMessages*: holds the messages
** *id*: unique ID
** *line1*: max. 40 alphanumeric characters
** *line2*: max. 100 alphanumaric characters

* *tblFeedback*: holds feedback from visitor
** *id*: unique ID
** *timestamp*: date/time
** *feedback*: one character, indicating positive, meh or negative feedback
** *extended*: alphanumeric text

== API

=== GetMessages

A GET request to /api/messages returns a list of all messages@. 

Request:

  GET /api/messages

Response:

  Status: 200 OK
  Content-Type: application/json
  Body: 
  [
    {
      "message-id": "15",
      "line1": "Back to the future",
      "line1": "The year is now 2106, but the issue remains. How do you intervene?"
    },
    {
      "message-id": "16",
      "line1": "last from the past",
      "line1": "Do it like it's 1921"
    },
    ...
  ]

=== GetMessage

A GET request to /api/messages/{message-id} returns one message. 

Request:

  GET /api/messages/15

Response when succesful:

  Status: 200 OK
  Content-Type: application/json
  Body:
  {
    "message-id": "16",
    "line1": "Blast from the past",
    "line1": "Do it like it's 1921"
  }

Response when the message doesn't exist:

  Status: 404 Not Found
  Content-Type: text
  Body: 
  Unknown message


=== CreateMessage

A message can be created by POSTing json to /api/messages.

Required fields:

* line1
* line2

Request:

  POST /api/messages
  Content-type: application/json
  Body:
  {
    "line1": "Blast from the past",
    "line2": "Do it like it's 1921"
  }


Respons bij succes:

  Status: 201 Created
  Content-Type: application/json
  Body: 
  {
    "id": 15,
    "line1": "Blast from the past",
    "line2": "Do it like it's 1921"
  }

=== UpdateMessage

A PUT request to /api/messages/{message-id} with json in the body of the request een json updates a message.

The message-id in the request must be the same as the message-id in the body. 

Request:

  PUT /api/messages/de:ca:fb:ad:27:08
  Content-Type: application/json
  Body: 
  {
    "message-id": "15", 
    "line1": "Blast from the past",
    "line2": "Do it like it's 1921"
  }

Response when succesful:

  Status: 201 Created
  Content-Type: application/json
  Body:
  {
    "message-id": "15", 
    "line1": "Blast from the past",
    "line2": "Do it like it's 1921"
  }

Response if the message does not exist:

  Status: 404 Not Found
  Content-Type: text
  Body: 
  Unknown message
